package com.orange.ai.reviewer_agent.web;

import com.orange.ai.reviewer_agent.application.review.ReviewOrchestrator;
import com.orange.ai.reviewer_agent.domain.review.ReviewComment;
import org.springframework.web.bind.annotation.*;

/**
 * REST Controller for code review operations
 */
@RestController
@RequestMapping("/api/review")
public class CodeReviewController {

    private final ReviewOrchestrator reviewOrchestrator;

    public CodeReviewController(ReviewOrchestrator reviewOrchestrator) {
        this.reviewOrchestrator = reviewOrchestrator;
    }

    /**
     * Triggers a complete code review for a merge request
     *
     * @param mrUri The GitLab merge request URI
     * @param sonarProjectKey The SonarQube project key
     * @return The review comment generated by AI
     */
    @PostMapping("/perform")
    public ReviewComment performReview(
            @RequestParam String mrUri,
            @RequestParam String sonarProjectKey) {
        return reviewOrchestrator.performCompleteReview(mrUri, sonarProjectKey);
    }

    /**
     * Webhook endpoint for GitLab to trigger review automatically
     */
    @PostMapping("/webhook/gitlab")
    public ReviewComment handleGitLabWebhook(@RequestBody GitLabWebhookPayload payload) {
        if (!"merge_request".equals(payload.objectKind()) ||
            !"opened".equals(payload.objectAttributes().action()) &&
            !"update".equals(payload.objectAttributes().action())) {
            throw new IllegalArgumentException("Webhook not for new/updated merge request");
        }

        String mrUri = payload.objectAttributes().url();
        // You might want to configure this or extract from project settings
        String sonarProjectKey = payload.project().pathWithNamespace().replace("/", "_");

        return reviewOrchestrator.performCompleteReview(mrUri, sonarProjectKey);
    }

    // DTOs for GitLab webhook
    record GitLabWebhookPayload(
            String objectKind,
            ObjectAttributes objectAttributes,
            Project project
    ) {
        record ObjectAttributes(String action, String url) {}
        record Project(String pathWithNamespace) {}
    }
}

